import { Page, View, Text, Image, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Inter',
    fontSize: 12,
    backgroundColor: '#ffffff',
    color: '#111111',
  },
  heading: {
    fontSize: 18,
    fontWeight: 600,
    marginBottom: 16,
    color: '#111111',
  },
  diagram: {
    width: 515,
    marginTop: 8,
  },
  caption: {
    marginTop: 8,
    fontSize: 10,
    color: '#888888',
    textAlign: 'center',
  },
  noImageBlock: {
    padding: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#dddddd',
    marginTop: 8,
  },
  noImageText: {
    color: '#777777',
    fontSize: 11,
    textAlign: 'center',
  },
})

interface TopologyPageProps {
  topoDiagramPng?: string
}

export function TopologyPage({ topoDiagramPng }: TopologyPageProps) {
  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.heading}>Topology Diagram</Text>
      {topoDiagramPng ? (
        <View>
          <Image src={topoDiagramPng} style={styles.diagram} />
          <Text style={styles.caption}>
            Dell Leaf-Spine topology — generated by NetStack
          </Text>
        </View>
      ) : (
        <View style={styles.noImageBlock}>
          <Text style={styles.noImageText}>
            Topology diagram not available — open the Topology tab before exporting.
          </Text>
        </View>
      )}
    </Page>
  )
}
